### ISSUE TITLE
How does ETH/USDT differentiate trading markets if there is a BTC/USDT

### ISSUE THREAD

**Issue by wunaigong** [ArjunVachhani/order-matcher#11]
How does ETH/USDT differentiate trading markets if there is a BTC/USDT.

**Comment by ArjunVachhani** [comment]
You will need to create one instance of MatchingEngine per market. So suppose you have 10 markets then you need to create 10 instance of MatchingEngine.

May be MatchingEngine name is bit confusing.

**Comment by wunaigong** [comment]
Thanks very much。

**Comment by wunaigong** [comment]
How to initialize billing records from the database

**Comment by ArjunVachhani** [comment]
`MatchingEngine` is in memory and state less so it will lose data on restart. So to initialize/re-initialize you need to add all the pending orders in sequence they are placed and you can get same state.

`MatchingEngine` does not support risk management/User Balance. So before adding new order you need to check for balance and probably lock balance. You should probably check for balance and lock balance when user places the order. While cancelling you need to cancel from `MatchingEngine` and then update permanent storage. `MatchingEngine` should be the source of the truth for order status.

**Few thing to consider**

- `MatchingEngine` is state less so it will lose data on restart.
- `MatchingEngine` should be the source of the truth for order status
- Risk Management/User balance is not part of `MatchingEngine`
- Adding orders in same sequence will lead to same state.
