### ISSUE TITLE
Support for distributed deployment

### ISSUE THREAD

**Issue by wunaigong** [ArjunVachhani/order-matcher#12]
Support for distributed deployment ？

**Comment by ArjunVachhani** [comment]
Can you please elaborate more? What you are looking for High Availability? or having few markets in machine A and rest of the markets in machine B?

**Comment by ArjunVachhani** [comment]
@wunaigong please re-open this bug if you need some info.

**Comment by ArjunVachhani** [comment]
@wunaigong I think correct way to do it is integrating order-matcher with any raft consensus implementation. Raft consensus algorithm takes care of distributed, high available and fault tolerant application. The only requirement for raft state machine is that state machine must be deterministic. order-matcher is a deterministic state machine.

Aeron cluster is implementation of raft.
