### ISSUE TITLE
What is the license for this project ?

### ISSUE THREAD

**Issue by 7E5x** [ArjunVachhani/order-matcher#24]
Hi, 
This matching engine seems very well designed, thank you for sharing it. I'm considering using it in a project. Could you please tell me what is the licence (GNU, MIT, Proprietary ...) of it ?
Also do you think that it can be extended (without too much effort) to support the "Price Pro-rata" matching algorithm (to fill order proportionally to their size for a given price) ?
Thank you !

**Comment by ArjunVachhani** [comment]
This repo is open source, you could use it for commercial use. I have not figured appropriate license at the moment but it will remain open source for sure.

I am not aware of implementation detail of "Price Pro-rata" algorithm so can not say how easy/difficult it would be. probably you could use order book.

**Comment by 7E5x** [comment]
Hi, thank you for your answer.
I believe that having a clear license for the Engine may help to get contributors but I understand that the choice of the license should not be taken lightly. 
I will test the engine more seriously and eventually contribute it. 
Best regards
