### ISSUE TITLE
matcher multithreading AddOrder supporting

### ISSUE THREAD

**Issue by avatar-92** [ArjunVachhani/order-matcher#29]
Is it correct to execute AddOrder from multiple threads in parallel or I should use locks for single thread work (execute AddOrder successively)?

**Comment by ArjunVachhani** [comment]
`AddOrder`, `CancelOrder` and `CancelExpiredOrder` are not thread safe and must be called sequentially.

**Comment by avatar-92** [comment]
Is the matcher ready for a production environment? Do you use it in your projects?

**Comment by ArjunVachhani** [comment]
@avatar-92 I don't have any projects related to exchange/matching engine, so we are not using it. I have not found any bug at the moment. Feel free to raise issue if you find any. 

Code in this repository is distributed under MIT license. Please read the license at [MIT license](https://github.com/ArjunVachhani/order-matcher/blob/master/LICENSE)

**Comment by avatar-92** [comment]
1. Can you add comments into class Order for clearify what properties I should set for add market/limit order?
2. State is CurrentOrders in MatchingEngine. I should save CurrentOrders, and add it after restart matcher.

**Comment by avatar-92** [comment]
I found MatchingEngineTests. Will see it for clearify,
