### ISSUE TITLE
Incorrect order deserialization

### ISSUE THREAD

**Issue by avatar-92** [ArjunVachhani/order-matcher#30]
In class OrderSerializerTests test Deserialize_Doesnotthrowexception I see creating order with OpenQuantity = 546 but on line 204 Assert.Equal((Quantity)2356, order.OpenQuantity);

Is it mistake in test and deserialization wrong?

**Comment by avatar-92** [comment]
What is difference between TotalQuantity, OpenQuantity, TipQuantity?

**Comment by ArjunVachhani** [comment]
### For Non Iceberg orders
You need to set only `OpenQuantity` for non iceberg orders. You don't need to set  `TipQuantity` and an `TotalQuantity`  for non iceberg orders. `OpenQuantity` means quantity user wants to buy/sell. Ideally you would set `OpenQuantity` to quantiy user wants to buy/sell.  After restart suppose you want to re initialize order book, You need to set `OpenQuantity` as remaining quantity for the order. 

### For Iceberg orders
You need to set  `TipQuantity` and an `TotalQuantity`  for iceberg orders. You don't need to set `OpenQuantity` for iceberg orders. `TotalQuantity` means quantity user want to buy/sell. `TipQuantity` means quantity of each tip added to orderbook. Ideally you would set `TotalQuantity` to quantiy user wants to buy/sell.  After restart suppose you want to re initialize order book, You need to set `TotalQuantity` as remaining quantity for the order.

**Comment by avatar-92** [comment]
Thanks for the comment
