### ISSUE TITLE
have question

### ISSUE THREAD

**Issue by vahidalvandi** [ArjunVachhani/order-matcher#32]
Hello
I need an open source maching engine that can process sales orders that are placed in the database through the app, that is, I can finally create something like a binance.
Please advise that this engine of yours can run alongside my app? For example, the membership and wallet sections should be deposited or withdrawn in the my app, and only the trading section should be run in this maching engine?

**Comment by ArjunVachhani** [comment]
This repo provide a order matcher, which will match buy and sell orders from your platform. order matcher can run along side your application. your application will handle deposits and withdraws. your application should maintain balance of users. you should send orders to order-matcher after validating user and balance. order-matcher has couple of events to update balance and order status. 

it does not provide all the features of binance.

**Comment by vahidalvandi** [comment]
Thanks for the tips.
I want to create different wallets and have different networks in my exchange. Please help me in this regard.

**Comment by ArjunVachhani** [comment]
wallets and networks are not part of order-matcher, it should be part of your solution

**Comment by vahidalvandi** [comment]
Yes I know . But I need some guidance

**Comment by ArjunVachhani** [comment]
I am not right person to guide you on wallets and network, You could probably read official documentation of wallets/network. Also there are wallet services providers as well.

**Comment by vahidalvandi** [comment]
Is this project a parallel thread? And did you get a benchmark performance from this project?

**Comment by ArjunVachhani** [comment]
No, order-matcher is not a parallel because of price time priority algo. We do not have performance/benchmark results

**Comment by ArjunVachhani** [comment]
@vahidalvandi I recently did a benchmark test and order-matcher is able to process 1Million order in a second on c5.xlarge ec3 instance.
