### ISSUE TITLE
Do you using Mather in production?

### ISSUE THREAD

**Issue by P9avel** [ArjunVachhani/order-matcher#37]
Please say, Do you using Mather in production?  If yes, how many Traders works in time? How many Instruments you have? How many Orders matching in second?

**Comment by ArjunVachhani** [comment]
I am personally not using order-matcher in production at the moment.

**Comment by P9avel** [comment]
Bad for me. in a couple of months I may need a matcher in one of my projects. I'm looking for something ready to production
