### ISSUE TITLE
Can you to add UserId long to Order?

### ISSUE THREAD

**Issue by P9avel** [ArjunVachhani/order-matcher#38]
Hi, i am need UserId in each Order. Can you to add UserId long to Order?

**Comment by ArjunVachhani** [comment]
At the moment UserId is not used by order-matcher. May I suggest you extending Order class

**Comment by P9avel** [comment]
I see you. But i am want to use your code as is and update when you will release new version without modification.

**Comment by P9avel** [comment]
I am need UserId and many users need to have UserId. i am think need add UserId to core and to serializatiors and etc

**Comment by ArjunVachhani** [comment]
At the moment UserId is not used, It will be needed If we implement Self Match Prevention(#6). If we have UserId property in Order then we might need to expose it to ITradeListener as well.

**Comment by ArjunVachhani** [comment]
@P9avel long-orderId-and-userId branch contains support for UserId and OrderId in long.
