### ISSUE TITLE
Do you support Move order to new price/count function?

### ISSUE THREAD

**Issue by P9avel** [ArjunVachhani/order-matcher#40]
Sometime need to move order without canceled. Do you have method for this?

**Comment by ArjunVachhani** [comment]
No, at the moment there is no support. If you are changing price then it must have change in priority. so cancel and new is also same.

**Comment by P9avel** [comment]
Cancel and Creating new then changed order datetime/queue.  When moving then your order can matched first in matching queue. But when Cancel and Creating new, then new order need put as last in matching queue.

**Comment by ArjunVachhani** [comment]
If you are changing quantity then your order in a queue will remain same.

**Comment by P9avel** [comment]
>>If you are changing quantity then your priority in a queue will remain same.

**Comment by P9avel** [comment]
Yes, agree

**Comment by P9avel** [comment]
>>if you cancel existing 98 order and create a new one at 99 in that case as well matching priority will remain same, you will come after all existing order at 99.

Yes, in your flow all ok. For example.  I am set Order001 Buy 1 by 90 in t1. Other user set order002 buy 1 by 100 in t2. After this i am moved Order001 to Buy 1 by 100, but my time t1. Next user set Order003 Sell 1 buy 100 in t3. I am wait what my Order001 will completed first (before Order002 because my order set in t1 and t1<t2)

**Comment by ArjunVachhani** [comment]
Change in price should reset priority, and modified order should come after all existing order at new price.

**Comment by ArjunVachhani** [comment]
Order002 execute first and then Order001 will execute, because of the price change
