### ISSUE TITLE
Multiple Markets

### ISSUE THREAD

**Issue by Kordeone** [ArjunVachhani/order-matcher#43]
I have a question about how this engine handles multiple market orders, as I have understood the engine only processes through one market, are you planning on adding this feature?

**Comment by ArjunVachhani** [comment]
one instance of MatchingEngine will handle one market, create multiple instances of MatchingEngine to handle multiple markets, there will be one instance of MatchingEngine for each market

**Comment by Kordeone** [comment]
So I would have about 100 MatchingEngine instances if I have 100 markets, right?
wouldn't this have negative effect on performance?

**Comment by Kordeone** [comment]
Many thanks to you sir
