### ISSUE TITLE
Market order with total price

### ISSUE THREAD

**Issue by sc-starman** [ArjunVachhani/order-matcher#54]
Hi
I wonder what is the best way to add market orders with total price instead of quantity.
let's say I want $2000 of something but don't care about how much I get in return.

**Comment by ArjunVachhani** [comment]
@sc-starman you do this for market buy order and stop loss market buy. for sell side this feature is not available


`Order marketBuy = new Order { IsBuy = true, Price = 0, OrderId = 12345, OrderAmount = 2000 };`
