### ISSUE TITLE
Self Match Prevention

### ISSUE THREAD

**Issue by ArjunVachhani** [ArjunVachhani/order-matcher#6]
Self Match Preventention feature prevents matching orders of the same user/account. Order Matching Engine will not match the buy & sell order of the same user/account. Users can specify what should happen in case of order executes against his/her orders. This feature will benefit users by avoiding matching his/her order. also, it benefits markets from the wash trade.

To opt-in for this feature, orders must specify UserId/AccountId and what action should be taken in case of a self match.

 - UserId/AccountId
 - Self Match Action(Any of below)
	 - Cancel Incoming Order
	 - Cancel Resting Order
	 - Reduce Quantity
	 - Match

**Comment by Kordeone** [comment]
Can I work on this?
